// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghstpjfvtcpmegwgkxiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoc3RwamZ2dGNwbWVnd2dreGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDcwODksImV4cCI6MjA2NTcyMzA4OX0.CI56-xohAZLFdZ9XlXTXrsCV5zPQDvpVoFB0FmDXrYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);